on:
  schedule:
    - cron:  '0 0 * * 1,4'
  workflow_dispatch:
jobs:
  scrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache-dependency-path: scrapper/go.sum
      - name: Lance le scrapping
        working-directory: ./scrapper
        run: go run cmd/main.go
      - uses: EndBug/add-and-commit@v9
        with:
          add: front/app/lib/poules.json
          default_author: github_actions
