on:
  schedule:
    - cron:  '0 0 * * 1,3,5'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Lance le scrapping
        working-directory: ./scrapper
        run: go run cmd/main.go